name: Build and Push Docker Image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual triggering
env:
  IMAGE_NAME: kasm-simplex
  KASM_BASE_IMAGE: kasmweb/ubuntu-jammy-desktop:1.16.1
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download latest SimpleX Chat
        id: simplex_version
        run: |
          chmod +x download_simplex.sh
          ./download_simplex.sh
          # Make sure we can read the outputs in subsequent steps
          SIMPLEX_VERSION=$(grep "version=" $GITHUB_OUTPUT | cut -d= -f2)
          SIMPLEX_FILE=$(grep "file=" $GITHUB_OUTPUT | cut -d= -f2)
          echo "Simplex version: $SIMPLEX_VERSION"
          echo "Simplex file: $SIMPLEX_FILE"
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            williamsct1/${{ env.IMAGE_NAME }}:latest
            williamsct1/${{ env.IMAGE_NAME }}:${{ steps.simplex_version.outputs.version }}
          build-args: |
            SIMPLEX_PACKAGE=${{ steps.simplex_version.outputs.file }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            williamsct1/${{ env.IMAGE_NAME }}:latest
            williamsct1/${{ env.IMAGE_NAME }}:${{ steps.simplex_version.outputs.version }}
          build-args: |
            SIMPLEX_PACKAGE=${{ steps.simplex_version.outputs.file }}